name: XCS224N_GPU
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.23.2
  - scipy=1.7.3
  - scikit-learn=1.1.1
  - matplotlib=3.5.3
  - tqdm=4.64.1
  - pytorch=1.12.0=py3.8_cuda11.3_cudnn8.3.2_0
  - docopt=0.6.2
  - torchvision=0.13.0
  - notebook
  - pip=22.1.2
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator